# Generated by Django 5.1.1 on 2024-10-21 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.TextField()),
                ('isFaceCut', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RawFaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.TextField()),
                ('rawfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawfiles.rawfiles')),
            ],
        ),
    ]
